[display]
width = 1366
height = 768

# left, right, top, bottom
direction = "bottom"

# 0, 90, 180, 270
rotation = 90

# I3 Workspaces that will be moved to virtual monitor
workspaces = [9, 10]

fps = 30

[server]
port = 8080
